export type item_model_tag = 
    'bow' 
    | 'spear' 
    | 'bone_spear' 
    | 'bone_dagger' 
    | 'sword' 
    | 'wooden_mace' 
    | 'rat_skin_pants'
    | 'rat_skin_armour'
    | 'bone_armour'
    | 'elodino_dress'
    | 'graci_hair'
    | 'rat_skull_helmet'
    | 'rat_skin_helmet'
    | 'rat_skin_boots'
    | 'rat_skin_gloves'
    | 'cloth_gloves'
    | 'cloth_armour'
    | 'cloth_helmet'